spring:
  application:
    name: myhomebuys

  datasource:
    url: jdbc:sqlite:myhomebuys.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  servlet:
    context-path: /myhomebuys
auth:
  client:
    public-key: http://localhost:8091/auth/public-key

logging:
  level:
    com.sro.myhomebuys: DEBUG